plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id
base { archivesName = mod_id }

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

repositories {
//    mavenLocal()
    flatDir {
        dirs("libs")
    }
    flatDir {
        dirs("zlib")
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://maven.su5ed.dev/releases"
    }

    maven { url = "https://maven.fallenbreath.me/releases" }


    maven { // Registrate
        url "https://maven.gegy.dev/releases"
        content { includeGroup "com.tterrag.registrate" }
    }
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
        server {
            server()
            programArgument '--nogui'
            gameDirectory = project.file('runs/server')
        }

        data {
            clientData()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        serverData {
            serverData()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/server_resources/').getAbsolutePath(), '--existing', file('src/main/server_resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }


}

sourceSets.main.resources {
    // Include resources generated by data generators.
    srcDir('src/generated/resources')

    // Exclude common development only resources from finalized outputs
    exclude("**/*.bbmodel") // BlockBench project files
    exclude("src/generated/**/.cache") // datagen cache files
}
//sourceSets.main.resources { srcDir 'src/generated/resources' }
sourceSets.main.resources { srcDir 'src/generated/server_resources' }

tasks.register('deleteCache') {
    delete 'src/generated/resources/.cache'
    delete 'src/generated/server_resources/.cache'
}

jar.dependsOn deleteCache

dependencies {
    // Specify the version of Minecraft to use.
    // Depending on the plugin applied there are several options. We will assume you applied the userdev plugin as shown above.
    // The group for userdev is net.neoforged, the module name is neoforge, and the version is the same as the neoforge version.
    // You can however also use the vanilla plugin (net.neoforged.gradle.vanilla) to use a version of Minecraft without the neoforge loader.
    // And its provides the option to then use net.minecraft as the group, and one of; client, server or joined as the module name, plus the game version as version.
    // For all intends and purposes: You can treat this dependency as if it is a normal library you would use.
//    implementation "net.neoforged:neoforge:${neo_version}"


    compileOnly "curse.maven:jei-238222:7850293"
    runtimeOnly "curse.maven:jade-324717:7817285"

    runtimeOnly "maven.modrinth:sodium:mc26.1.2-0.8.12-beta.1-neoforge"
    runtimeOnly "maven.modrinth:iris:1.10.9+26.1-neoforge"

    implementation "curse.maven:inventory-sorter-240633:7940779"

    implementation("me.fallenbreath:conditional-mixin-neoforge:0.6.4")

    implementation("me.fallenbreath:conditional-mixin-neoforge:0.6.4")
    jarJar(implementation("me.fallenbreath:conditional-mixin-neoforge:0.6.4"))

    println("----Scan onlyMainRuntimeOnly libs begin----")
    runtimeOnly "com.tterrag.registrate:Registrate:MC26.1-1.5.0"

    fileTree(dir: 'libs', include: ['*.jar']).each { File file ->
        def fileName = file.name
        println(fileName.substring(0, fileName.indexOf("-")) + "," + fileName.substring(fileName.indexOf("-") + 1, fileName.indexOf(".jar")))
        runtimeOnly(name: fileName.substring(0, fileName.lastIndexOf(".jar")),
                group: 'libs',
                version: fileName.substring(0, fileName.indexOf(".jar")))
    }
    println("----Scan onlyMainRuntimeOnly libs end----")
}
processResources {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            neoforge_version: neo_version,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}
