org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
neo_version=26.1.2.71

mod_id=fresh_food
mod_name=Fresh Food
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.teamtea.fresh_food
mod_authors=Vettek Joe
mod_description=A small food rot mod for Minecraft 26.1 NeoForge.
